version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

image:
  - Ubuntu
  - Visual Studio 2017

environment:
  matrix:
    - BUILD_COMBO: windows-mingw
    - BUILD_COMBO: windows-msvc
    - BUILD_COMBO: linux-gcc    
    - BUILD_COMBO: linux-clang

matrix:
  exclude:
    - image: Visual Studio 2017
      BUILD_COMBO: linux-gcc
    - image: Visual Studio 2017
      BUILD_COMBO: linux-clang
    - image: Ubuntu
      BUILD_COMBO: windows-mingw
    - image: Ubuntu
      BUILD_COMBO: windows-msvc


configuration:
  - Debug
  - Release

install:
  - ps: ./ci/setup.ps1

build_script:
  - ps: ./ci/build.ps1

test_script:
  - ps: ./ci/test.ps1
