version: 1.1.5-{build}

image:
  - Visual Studio 2017
  - Ubuntu1604

environment:
  matrix:
    - BUILD_COMBO: windows-mingw
    - BUILD_COMBO: windows-msvc
    - BUILD_COMBO: linux-gcc    
    - BUILD_COMBO: linux-clang

matrix:
  exclude:
    - image: Visual Studio 2017
      BUILD_COMBO: linux-gcc
    - image: Visual Studio 2017
      BUILD_COMBO: linux-clang
    - image: Ubuntu1604
      BUILD_COMBO: windows-mingw
    - image: Ubuntu1604
      BUILD_COMBO: windows-msvc


configuration:
  - Debug
  - Release

install:
  - ps: ./ci/setup.ps1

build_script:
  - ps: ./ci/build.ps1

test_script:
  - ps: ./ci/test.ps1

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
