language: cpp
compiler:
- gcc
- clang
os:
- linux
script: cmake -G Ninja ./build; ./build/tests/pkg_test
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
branches:
  only:
    - master
    - "^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$"